# Yazi Configuration File
# https://yazi-rs.github.io/docs/configuration/overview

[mgr]
layout = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5

# Set a predictable title format for window managers
title_format = "Yazi: {cwd}"

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_filter = "lanczos3"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = '${EDITOR:=nvim} %s', block = true, desc = "Edit", for = "unix" },
  { run = 'code %s', orphan = true, desc = "Code", for = "windows" },
]
open = [
  { run = 'xdg-open %s', desc = "Open", for = "linux" },
  { run = 'open %s', desc = "Open", for = "macos" },
  { run = 'start "" %s1', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { run = 'xdg-open %d1', desc = "Reveal", for = "linux" },
  { run = 'open -R %s1', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,%s1', orphan = true, desc = "Reveal", for = "windows" },
]
extract = [
  { run = 'unar %s1', desc = "Extract here", for = "unix" },
  { run = 'unar %s1', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'mpv %s', orphan = true, for = "unix" },
  { run = 'mpv %s1', orphan = true, for = "windows" },
]

[open]
rules = [
  { mime = "inode/directory", use = [
    "edit",
    "open",
    "reveal",
  ] },
  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  { mime = "video/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "audio/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "inode/x-empty", use = [
    "edit",
    "reveal",
  ] },
  { mime = "application/json", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*", use = [
    "open",
    "reveal",
  ] },
]
