#!/usr/bin/env bash
# Deploy Limine to the ESP and boot the linux-lts UKI by default. playbook.yml
# installs this as /usr/local/libexec/chezmoi-limine-sync and runs it as root;
# the 99-limine pacman hook reruns it after limine or kernel changes.
# Idempotent: prints a "changed:" line for each thing it had to fix.

set -euo pipefail

(( EUID == 0 )) || { printf 'must run as root\n' >&2; exit 1; }

esp=/boot
loader_dir="$esp/EFI/limine"
uki_dir="$esp/EFI/Linux"
conf="$loader_dir/limine.conf"
loader='\EFI\limine\BOOTX64.EFI'

[[ $(findmnt -n -o FSTYPE "$esp") == vfat ]] || { printf '%s is not a vfat ESP\n' "$esp" >&2; exit 1; }
# Never point firmware at a config with no working default entry.
[[ -f $uki_dir/arch-linux-lts.efi ]] || { printf 'missing %s/arch-linux-lts.efi; run mkinitcpio -p linux-lts\n' "$uki_dir" >&2; exit 1; }

install -d "$loader_dir"
if ! cmp -s /usr/share/limine/BOOTX64.EFI "$loader_dir/BOOTX64.EFI"; then
  install -m 0644 /usr/share/limine/BOOTX64.EFI "$loader_dir/BOOTX64.EFI"
  printf 'changed: deployed %s/BOOTX64.EFI\n' "$loader_dir"
fi

entry() {
  if [[ -f $uki_dir/$2 ]]; then
    printf '/%s\n    protocol: efi\n    path: boot():/EFI/Linux/%s\n\n' "$1" "$2"
  fi
}

desired=$(
  printf '# Generated by chezmoi-limine-sync; edits are overwritten.\ntimeout: 3\ndefault_entry: 1\n\n'
  entry 'Arch Linux (linux-lts)' arch-linux-lts.efi
  entry 'Arch Linux (linux-lts, fallback initramfs)' arch-linux-lts-fallback.efi
  entry 'Arch Linux (linux)' arch-linux.efi
  entry 'Arch Linux (linux, fallback initramfs)' arch-linux-fallback.efi
)
if [[ ! -f $conf ]] || [[ $(<"$conf") != "$desired" ]]; then
  printf '%s\n' "$desired" >"$conf.new"
  mv -f "$conf.new" "$conf"
  printf 'changed: wrote %s\n' "$conf"
fi

part_dev=$(findmnt -n -o SOURCE "$esp")
partuuid=$(lsblk -n -o PARTUUID "$part_dev")
find_entry() {
  efibootmgr | awk -v uuid="${partuuid,,}" '
    tolower($0) ~ uuid && tolower($0) ~ /\\efi\\limine\\bootx64\.efi/ {
      sub(/^Boot/, "", $1); sub(/\*$/, "", $1); print $1; exit
    }'
}

num=$(find_entry)
if [[ -z $num ]]; then
  disk="/dev/$(lsblk -n -o PKNAME "$part_dev")"
  partnum=$(<"/sys/class/block/${part_dev##*/}/partition")
  efibootmgr --create --disk "$disk" --part "$partnum" --label Limine --loader "$loader" >/dev/null
  num=$(find_entry)
  [[ -n $num ]] || { printf 'failed to create the Limine boot entry\n' >&2; exit 1; }
  printf 'changed: created boot entry Boot%s\n' "$num"
fi

order=$(efibootmgr | sed -n 's/^BootOrder: //p')
if [[ ${order%%,*} != "$num" ]]; then
  rest=$(tr ',' '\n' <<<"$order" | grep -vx -- "$num" | paste -sd, || true)
  efibootmgr --bootorder "$num${rest:+,$rest}" >/dev/null
  printf 'changed: boot order %s -> %s\n' "$order" "$num${rest:+,$rest}"
fi
